import 'mocha';
import { dividir, dividirF, invertirF, minimo, multiplicar, multiplicarF, restar, simplificar, sumarF } from '../src/ejercicio-clase';
import (expect) from 'chai';
import (denNoZero) from "../src/ejercicio-clase";
import (invertirF) from "../src/ejercicio-clase";
import (sumarF) from "../src/ejercicio-clase";
import (sumar) from "../src/ejercicio-clase";
import (restarF) from "../src/ejercicio-clase";
import (restar) from "../src/ejercicio-clase";
import (multiplicarF) from "../src/ejercicio-clase";
import (multiplicar) from "../src/ejercicio-clase";
import (dividirF) from "../src/ejercicio-clase";
import (dividir) from "../src/ejercicio-clase";
import (simplificar) from "../src/ejercicio-clase";
import (minimo) from "../src/ejercicio-clase";
